const after_html = document.querySelector(".test-diagram-1")
const cg = new Connectogram(after_html, "diagram1")
const blobRect = cg.addBlob("blobRect1", "rectangle", {height: 150, width: 140}, 120, 50, "black", "blue")
const blobRect2 = cg.addBlob("blobRect2", "rectangle", {height: 150, width: 140}, 600, 200, "black", "blue")
const blobCirc = cg.addBlob("blob2", "circle", {radius: 70}, 500, 79, "pink", "blue")
const blobEllip = cg.addBlob("blob3", "ellipse", {radiusx: 120, radiusy: 60}, 400, 400, "red", "blue")
// cg.removeBlob("blob1")
// blobRect.changeWidth(10)
// log(cg.changeBlobName("blob1", "blob4"))
blobRect.changeColor("Green")
cg.connect(blobRect, blobRect2)
cg.connect(blobCirc, blobEllip)
cg.connect(blobCirc, blobRect)
blobRect.addText("Hello Sir", "Sans-Serif", "20px", "center", "pink")
blobRect.addText("Hello Sir", "Sans-Serif", "20px", "left", "pink")
blobRect.addText("Hello Sir", "Sans-Serif", "20px", "right", "pink")
blobCirc.addText("Hello Sir", "Sans-Serif", "20px", "center", "black")
blobCirc.addText("Hello Sir", "Sans-Serif", "20px", "left", "black")
blobCirc.addText("Hello Sir", "Sans-Serif", "20px", "right", "black")
blobEllip.addText("Hello Sir", "Sans-Serif", "20px", "center", "blue")
blobEllip.addText("Hello Sir", "Sans-Serif", "20px", "left", "blue")
blobEllip.addText("Hello Sir", "Sans-Serif", "20px", "right", "blue")
blobRect.textAlign("Right")
blobRect.setPosition(130, 260)
// blobRect.clearText()
